spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: uAiqwVwjJ8-iguojian
    url: jdbc:mysql://123.56.11.62:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level:
    root: debug

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mpAppId: wx3e08416263e5eaa6
  mpAppSecret: 6a98b0ea97dd3c830d900870e33d53ba #借用号appId,appSecret
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #开放平台测试号appId,appSecret
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #借用帐号appId,appSecret
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:/Users/Administrator/Downloads/h5.p12
  notifyUrl: http://sqmax.natapp1.cc/notify
  templateId:
    orderStatus: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

projectUrl:
  wechatMpAuthorize: http://shiyue.cross.echosite.cn
  wechatOpenAuthorize: http://shiyue.cross.echosite.cn
  sell: http://shiyue.cross.echosite.cn
